package proba
import io.gatling.core.Predef._
import io.gatling.http.Predef._

object Action {
  val request_0_to_wt = http("request_0_to_wt")
    .get("/webtours/")
    .check(status is 200)
  val request_3_session = http("request_3_session")
    .get("/cgi-bin/nav.pl?in=home")
    .check(regex("""name="userSession" value="(.+)"""").saveAs("userSession"))
    .check(status is 200)
  val request_5_autoriz = http("request_5_autoriz")
    .post("/cgi-bin/login.pl")
    .formParam("userSession", "${userSession}")//132450.097205346ziVcQAVpiHftAiHHptVVcf
    .formParam("username", "${login}")
    .formParam("password", "${psw}")
    .formParam("login.x", "66")
    .formParam("login.y", "8")
    .formParam("JSFormSubmit", "off")
    .check(status is 200)
  val request_15_to_fly = http("request_15_to_fly")
    .get("/cgi-bin/welcome.pl?page=search")
  val request_16_get_reservations = http("request_16_get_reservations")
    .get("/cgi-bin/reservations.pl?page=welcome")
    .check(status is 200)
    .check(regex( """<option (?:selected=\"selected\" value=\"|value=\")(.+)\">""").findAll.saveAs("arrReservations"))
    //.check(xpath())
    //.check(css("#depart","option value").findAll.saveAs("arrReservations"))
  val request_21_set_param_fly  = http("request_21_set_param_fly")
    .post("/cgi-bin/reservations.pl")
    .formParam("advanceDiscount", "0")
    .formParam("depart", "${depart}")
    .formParam("departDate", "10/25/2021")
    .formParam("arrive", "${arrive}")
    .formParam("returnDate", "10/27/2021")
    .formParam("numPassengers", "1")
    .formParam("seatPref", "Window")
    .formParam("seatType", "First")
    .formParam("findFlights.x", "43")
    .formParam("findFlights.y", "5")
    .formParam(".cgifields", "roundtrip")
    .formParam(".cgifields", "seatType")
    .formParam(".cgifields", "seatPref")
    .check(status is 200)
    .check(regex( """name="outboundFlight" value="(.*?)10/""").findAll.saveAs("arrOutbound"))
  val request_22_set_param_fly_ex = http("request_22_set_param_fly_ex")
    .post("/cgi-bin/reservations.pl")
    .formParam("outboundFlight", "${outbound}10/25/2021")
    .formParam("numPassengers", "1")
    .formParam("advanceDiscount", "0")
    .formParam("seatType", "First")
    .formParam("seatPref", "Window")
    .formParam("reserveFlights.x", "47")
    .formParam("reserveFlights.y", "13")
    .check(status is 200)
  val request_23_set_param_pass = http("request_23_set_param_pass")
    .post("/cgi-bin/reservations.pl")
    .formParam("firstName", "${first_name}")
    .formParam("lastName", "${last_name}")
    .formParam("address1", "street333")
    .formParam("address2", "City333")
    .formParam("pass1", " Va")
    .formParam("creditCard","${card}")
    .formParam("expDate", "1109")
    .formParam("oldCCOption", "")
    .formParam("numPassengers", "1")
    .formParam("seatType", "First")
    .formParam("seatPref", "Window")
    .formParam("outboundFlight", "${outbound}10/25/2021")
    .formParam("advanceDiscount", "0")
    .formParam("returnFlight", "")
    .formParam("JSFormSubmit", "off")
    .formParam("buyFlights.x", "42")
    .formParam("buyFlights.y", "17")
    .formParam(".cgifields", "saveCC")
    .check(status is 200)
  val request_24_to_menu = http("request_24_to_menu")
    .get("/cgi-bin/welcome.pl?page=menus")
    .check(status is 200)
}
